%.html: %.org
	/opt/fox/fox html --org $< \
		--template /opt/fox/templates/simple.html \
		--css simple.css \
		--header "" \
		--head "<link rel=\"icon\" type=\"image/x-icon\" href=\"favicon.png\">" \
		--footer "©Copyright JHJ Technology Limited | Company Number 12418911 | Generated by Fox"  > $@

SRC := $(wildcard *.org)
OUT := $(patsubst %.org,%.html,$(SRC))

CSS=simple.css

or: $(OUT) $(CSS)
	@echo "Building"

clean:
	@echo "Cleaning.."
	rm -rf $(OUT)
